esphome:
  name: esp-lampen

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "97d86ee2e76111ac3e4317243236c12f"

wifi:
  ssid: #type network name here
  password: #type network password here

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Lampen Fallback Hotspot"
    password: "MmOJCqKbcmUV"

captive_portal:

switch:
  - platform: gpio
    pin: GPIO16
    name: "LED boven kamer rechts"
  - platform: gpio
    pin: GPIO5
    name: "LED boven kamer midden"
  - platform: gpio
    pin: GPIO4
    name: "LED bover kamer links"
  - platform: gpio
    pin: GPIO14
    name: "LED inkom"
  - platform: gpio
    pin: GPIO12
    name: "LED living 1"
  - platform: gpio
    pin: GPIO13
    name: "LED living 2"
  - platform: gpio
    pin: GPIO15
    name: "LED keuken"
